#!/bin/bash

# read all arguments
MY_ARG="$@"

# read file path from the argument
MY_FILE=`echo "$MY_ARG" | sed "s/^\([^:]*\).*/\1/"`

# skip all in the argument that is not ':'
MY_ARG=`echo "$MY_ARG" | sed "s/^[^:]*\(.*\)/\1/"`

# skip the ':' and all after it that is not a number
MY_ARG=`echo "$MY_ARG" | sed "s/^:[^0-9]*\(.*\)/\1/"`

# take the number as line number
MY_ROW=`echo "$MY_ARG" | sed "s/^\([0-9]*\).*/\1/"`

# skip all that is not ':'
MY_ARG=`echo "$MY_ARG" | sed "s/^[^:]*\(.*\)/\1/"`

# skip the ':' and all after it that is not a number
MY_ARG=`echo "$MY_ARG" | sed "s/^:[^0-9]*\(.*\)/\1/"`

# take the number as column number
MY_COLUMN=`echo "$MY_ARG" | sed "s/^\([0-9]*\).*/\1/"`

# call vim
if [ -z $MY_ROW ]; then

	# if only the file path is given
	vim $MY_FILE
else
	if [ -z $MY_COLUMN ]; then

		# if only file path and line number are given
		vim +$MY_ROW $MY_FILE
	else

		# if file path, line number, and column number are given
		vim +"call cursor($MY_ROW, $MY_COLUMN)" $MY_FILE
	fi
fi
